### PR TITLE
Relhajj bugs

### LINKED ISSUE #16: Add URL links to maven repository entries for all libraries
Insert a commented url with each replacement on the build.gradle file. 
The comment will be a URL that takes user to that library entry in the maven repository where they can see info on that library and the version number etc. 

This would require these changes:
- add a URL column in the libcomp DB on smr and populate all 50 libraries with the relevant links 
- add the URL to the GET API when we get all of the library data
- change the replacement string in the plugin

### LINKED ISSUE #21: Trigger LibComp on save file and file open
Current functionality of LibComp:
* on project load, all open editors are analyzed and all .java or build.gradle file(s) with relevant libraries will be highlighted accordingly

* AFTER project has already loaded, if the user opens a new file in the project and wishes to have LibComp analyze it then have to (1) open the file and then (2) right click with their mouse/mousepad 

GOAL/WHAT THIS ISSUE IS FOR:

* instead of the right click triggering the action for new files opened, make it so the action is triggered on file opened

### LINKED ISSUE #25: Save feedback locally until permission given
Save all feedback locally:
1. if no permission given 
2. no internet 

Once permission given OR internet comes back:
* send and delete feedback

### LINKED ISSUE #27: Highlighting stays there even if import is changed
1- Try adding an import statement we have info about e.g., `import org.junit.*`
2- make sure it gets highlighted
3- change that import statement to anything else e.g., `import javax.accessibility.Accessible;`, the line will remain highlighted which it shouldn't be

image

### LINKED ISSUE #28: Wrong class name captured for replacements
It seems that the class name of the action rather than the class name of *where* the action was taken is recorded:

```
 33 | 2020-06-11 12:54:50.000000 |       14 | IntelliJGradle | smr.cs.ualberta.libcomp.action.ReplacementAction | 6,5           |               6 |             5 |      46 |
```

`smr.cs.ualberta.libcomp.action.ReplacementAction` should be whatever java file or build file the replacement was done in

### LINKED ISSUE #34: More structured gradle parsing
Right now, it seems we use text-based regular expressions for parsing gradle dependencies. Similar to how we use PSI for Java files, there must be a parser for gradle files that we can use (Given that IntelliJ can recognize incorrect syntax there)

### PR DESCRIPTION
**Pull request by relhajj**
This PR deals with solving several issues below:
* closes #21 
* closes #25 
* closes #27 
* closes #28 
* closes #34
* closes #16

Also, when reviewing you might benefit from filtering to only see the .java files as those are what changed.

### CODE REVIEW

File: PluginCode/src/main/java/PostStartupActivity.java [hunk 1]
```diff
@@ -34,9 +39,21 @@ public void selectionChanged(@NotNull FileEditorManagerEvent event) {
                 } catch (IOException e) {
                     e.printStackTrace();
                 }
+            } // public void selectionChanged
```
Comment (snadi) [inline PluginCode/src/main/java/PostStartupActivity.java:42]: What is this comment?

File: PluginCode/src/main/java/PostStartupActivity.java [hunk 2]
```diff
@@ -34,9 +39,21 @@ public void selectionChanged(@NotNull FileEditorManagerEvent event) {
...
+        });
 
+        connection.subscribe(VirtualFileManager.VFS_CHANGES, new BulkFileListener() {
+            @Override
+            public void after(@NotNull List<? extends VFileEvent> events) {
+                // handle the events
```
Comment (snadi) [inline PluginCode/src/main/java/PostStartupActivity.java:48]: which events? Can you be specific so it's easy in the future to understand the code?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 3]
```diff
@@ -31,6 +33,7 @@
     private static Session session = null;
     private int userid = 0;
     private String filePath = PathManager.getPluginsPath()+"\\Library_Comparison\\lib";
+    private String feedbackUrllink = "https://smr.cs.ualberta.ca/comparelibraries/api/pluginfeedback/";
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:36]: It might be a good idea (perhaps open a new enhancement issue) to move all urls, paths etc to a configuration file. let's say we changed the REST API urls, we shouldn't need to edit or recompile the code.

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 4]
```diff
@@ -394,7 +397,7 @@ public boolean sendFeedback(String urlStr, String jsonBodyStr, String tokenValue
         }
 
         try {
-            if (httpURLConnection.getResponseCode() == HttpURLConnection.HTTP_OK) {
+            if (httpURLConnection.getResponseCode() == 201) {
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:400]: Why this change? Is HTTP_OK != 201? Using the named value is more readable

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 5]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
 
         if (Integer.parseInt(userRecord.getCloudStore()) == 1) {
             sendUser(userRecord.getUserID(), obj.toString());
+
+            sendFeedbackToCloud(); // check if the user has local feedback stored previously, send them now.
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:488]: What's teh difference between `sendFeedback` above? and `sendFeedbackToCloud()`?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 6]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
         }
     }
 
-    public void updateFeedback(ReplacementFeedback replacementFeedback) throws IOException {
+    public void storeLocalFeedback(JSONObject obj) throws IOException {
+
+        String filePath = this.filePath +"\\Feedback.json";
+        File myFile = new File(filePath);
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:495]: use a descriptive name.. not myFile

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 7]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
             sendUser(userRecord.getUserID(), obj.toString());
+
+            sendFeedbackToCloud(); // check if the user has local feedback stored previously, send them now.
         }
     }
 
-    public void updateFeedback(ReplacementFeedback replacementFeedback) throws IOException {
+    public void storeLocalFeedback(JSONObject obj) throws IOException {
+
+        String filePath = this.filePath +"\\Feedback.json";
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:494]: use descriptive name `localFeedbackPath` for example

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 8]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+        File myFile = new File(filePath);
+        JSONObject Mainobj = null; // = new JSONObject();
+        if (myFile.exists()) {
+            String content = FileUtils.readFileToString(myFile, "utf-8");
+            JSONObject objM = new JSONObject(content);
+            JSONArray jsonarr = objM.getJSONArray("Feedbacks");
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:500]: Is Feedbacks (plural) an actual word?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 9]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+            jsonarr.put(obj);
+            Mainobj = new JSONObject();
+            Mainobj.put("Feedbacks", jsonarr);
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:503]: what is `Mainobj`? can you choose a more descriptive name?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 10]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+        } else
+        {
+            Mainobj = new JSONObject();
+            JSONArray array = new JSONArray();
+            array.put(obj);
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:508]: What is `array`? again, descriptive name

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 11]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+        myOutWriter.append(result);
+        myOutWriter.close();
+    }
+
+    public void sendFeedbackToCloud() throws IOException {
+        String filePath = this.filePath +"\\Feedback.json";
+        String tokenValue = getUserToken();
+        File myFile = new File(filePath);
+        boolean successfulsent = false;
+        if (myFile.exists()) {
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:524]: Ok, so same comment for everything about names.. and be consistent in variable name style (camel case)

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 12]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+            int i = 0;
+            while (i<jsonarr.length() )
+            {
+                JSONObject jsonObj = (JSONObject)jsonarr.get(i);
+                jsonObj.put("user", this.userid);
+                String JsonString = jsonObj.toString();
+                if (sendFeedback(JsonString, tokenValue)) {successfulsent = true;}
+                i++;
+            }
+            if (successfulsent) {Files.deleteIfExists(Paths.get(filePath));}
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:537]: hmm, but what if it was able to send one of the feedback entries then failed on the rest, you are still going to delete everything because you set the flag if *any* is sent?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 13]
```diff
@@ -500,11 +554,19 @@ public void updateFeedback(ReplacementFeedback replacementFeedback) throws IOExc
         obj.put("action_date", df.format(replacementFeedback.getAction_date()));
 
         String JsonString = obj.toString();
-        String InsertUrllink = "https://smr.cs.ualberta.ca/comparelibraries/api/pluginfeedback/";
+        if (cloudSelect)
+        {
+            if (sendFeedback(JsonString, tokenValue)) {}
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:559]: what is the point of this empty if statement?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java [hunk 14]
```diff
@@ -129,42 +131,71 @@ public void detectAllOpenEditors() throws IOException {
...
+        {
             int startOffset = document.getLineStartOffset(i);
             int endOffset = document.getLineEndOffset(i);
             lineText = document.getText(new TextRange(startOffset, endOffset)).trim();
-
-            // checking values between single quotes in dependencies in build.gradle file
-            // check te first value, "group", as the selectedTerm
-            if (searchMode) {
-                String[] valuesInQuotes = StringUtils.substringsBetween(lineText, "\'", "\'");
+            String[] valuesInQuotes = StringUtils.substringsBetween(lineText, "\'", "\'");
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java:193]: hmm, if you have a PSI representation, why do you need to do substrings etc?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java [hunk 15]
```diff
@@ -256,11 +285,19 @@ public void replaceRequestedImport(@NotNull final AnActionEvent event) throws Pa
         final Editor editor = event.getRequiredData(CommonDataKeys.EDITOR);
         final Project project = event.getRequiredData(CommonDataKeys.PROJECT);
         final Document document = editor.getDocument();
+        PsiFile file = PsiDocumentManager.getInstance(project).getPsiFile(document);
+
+        String project_name = project.getName();
+        String class_name = "";
+        if (file instanceof PsiJavaFile) {
+            PsiClass[] clazzes = ((PsiJavaFile) file).getClasses();
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java:293]: `clazzes` ? what "classes" ?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java [hunk 16]
```diff
@@ -481,16 +484,67 @@ public void updateUserProfile(User userRecord) throws IOException {
...
+    }
+
+    public void updateFeedback(boolean cloudSelect, ReplacementFeedback replacementFeedback) throws IOException {
 
         String tokenValue = getUserToken();
         JSONObject obj = new JSONObject();
         DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
-
-        obj.put("user", this.userid);
+        if (cloudSelect) {obj.put("user", this.userid);} // no userid to be stored locally, as it is not yet set
```
Comment (snadi) [inline PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:547]: what does cloudSelect do?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 3 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:36]: Ok I opened a new issue for this

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 4 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:400]: ok, now using the named variables

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 5 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:488]: sendFeedbackToCloud() will loop over all feedback entries and call sendFeedback() for each single entry
sendFeedback() sends a single json entry to smr

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 6 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:495]: renamed to localFeedbackFile

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 8 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:500]: changed to Feedback

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 9 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:503]: renamed to feedbackObject

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 10 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:508]: renamed to feedbackEntryArray

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 11 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:524]: renamed to feedbackFile

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 12 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:537]: So I changed successfulSent from a boolean to a counter/integer to track that they are all taken account for. 
So now, the json file will be deleted after they are all sent.

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 13 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:559]: removed

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java (hunk 14 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java:193]: because for gradle PSI they only detect nodes (ex: dependencies), but inside the node I still need to parse it.

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 16 above)
Comment (relhajj) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:547]: renamed to sendToCloud, which is a boolean for whether or not it should be sent or stored only locally

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 5 above)
Comment (snadi) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:488]: So as you can see both actually send feedback to the cloud but their names don't distinguish that. Perhaps it should just be
`sendAllLocalFeedback`
and `sendFeedbackEntry`

or 
`sendFeedback`
and `sendFeedbackEntry`

something that indicates that one loops over everything while the other is a helper/subtask method to send a single entry

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java (hunk 12 above)
Comment (snadi) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/DatabaseAccess.java:537]: Ok, what happens if you send some and some not? Will you then send all again the next time causing duplicate feedback entries in the remote DB?

File: PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java (hunk 14 above)
Comment (snadi) [reply PluginCode/src/main/java/smr/cs/ualberta/libcomp/action/ReplacementAction.java:187]: I would assume that you will get a dependencies node and then inside it can get dependency by dependency and inside each dependency get the individual attributes such as group etc ?

**Comment by snadi** [comment]
@relhajj I have merged the PR on the server and now the maven url should be returned by the API. However, note that you should also open a PR in the LibraryMetricScripts repo to update:

- [https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/scripts/SharedFiles/LibraryData.json](https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/scripts/SharedFiles/LibraryData.json) -- add field there for each entry

- [https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/scripts/addlibraries.py](https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/scripts/addlibraries.py) to add that entry for future libraries or if we reset the DB

- [https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/librarycomparison/models.py](https://github.com/ualberta-smr/LibraryMetricScripts/blob/master/librarycomparison/models.py) to have the same model as the website (till we find an easier way to avoid having this model in two places)
